### ISSUE TITLE
Security for the command interface

### ISSUE THREAD

**Issue by juntao** [second-state/SSVM#138]
Add a WASI option to list external commands this SSVM instance is allowed to call. Unlisted commands should fail with a security exception.

**Comment by hydai** [comment]
Is this feature related to `process` module?

**Comment by hydai** [comment]
So we will provide two options:

1. `--allow-commands=ls,echo,gcc` : This will make the `process` module checks the calling commands is in the allowlist or not. If not, throw error.
2. `--allow-all-commands`: This means the `process` module will bypass the command to host without checking.
