### ISSUE TITLE
fibonacci.wasm run too slower in ssvm than node

### ISSUE THREAD

**Issue by Litrop** [second-state/SSVM#158]
I use [fibonacci.wasm](https://github.com/second-state/SSVM/blob/master/tools/ssvm/examples/fibonacci.wasm) to write a [simple benchmark](https://github.com/Litrop/ssvm-benchmark) between SSVM and node.
In my computer(WSL), `fib 40` cost 40s in SSVM but 1s in node. Any idea or reason for that?

**Comment by hydai** [comment]
Because the execution model is different.

Node.js uses Just-in-Time compilation. And the default execution engine of SSVM is interpreter mode. That's why it will take more time in the fibonacci example.

You can also try our Ahead-of-Time compilation mode:

```bash
start=$(date +%s)
result=$(ssvmc fibonacci.wasm a.so)
end=$(date +%s)
echo ssvmc cost:$(($end - $start))s result:$result
start=$(date +%s)
result=$(ssvm --reactor a.so fib 40)
end=$(date +%s)
echo ssvm cost:$(($end - $start))s result:$result
```

And you will find the performance is better than using interpreter mode.

**Comment by Litrop** [comment]
I'm not agree with `Node.js uses Just-in-Time compilation`, node need to compile wasm and get instance before use it.
But impressive performance in AOT mode.
Closed and thanks.

**Comment by hydai** [comment]
Ah. I said something wrong. The wasm is compiled and instantiate in the node. Thanks for clarification.

**Comment by hydai** [comment]
Thanks for your comments.
I found that I am also confused by the V8 wasm compilation pipeline.
V8 has Liftoff, a single-pass compiler.
Also, V8 has TurboFan, a multi-pass compiler which is described at below:

https://stackoverflow.com/a/59812253

> V8 developer here. Just to clarify and expand what commenters have been pointing out already:
> 
> "JIT" means "just in time", and means that some execution environment dynamically (i.e. at runtime) decides to produce something (typically machine code -- colloquially, "JIT" tends to mean "just-in-time compilation", although if you decide to prepare a meal exactly when you're hungry and then eat it right away when it's done, then that's technically also "JIT" preparation.) The canonical opposite would be a language like C/C++, which is compiled by the developer, long before being delivered to and executed by the user. Another "opposite" in a different direction is an execution environment that executes something without producing machine code dynamically. Such environments are typically called "interpreters".
> 
> In the past, V8 used to always produce machine code. It simply had no way to execute JavaScript that did not involve compiling it to machine code first. Obviously this happened on the client, so it was a textbook example of a just-in-time compiler (or, more accurately, a set of several compilers... oh well, details!).
> 
> In recent years, V8 has had an interpreter as its first execution tier. Now usage of terms gets complicated, because this interpreter "compiles" JavaScript "just in time" to bytecode (which is then interpreted), but when someone says "JIT compiler", they usually mean that it's not an interpreter.
> 
> V8 also has an optimizing compiler that produces machine code. It runs at runtime (when a function is considered hot), so it's a just-in-time compiler.

**Comment by Litrop** [comment]
```
ssvmc fibonacci.wasm fibonacci.so
```
`fibonacci.wasm` is __assembly__.
`fibonacci.so` is __machine code__.
You mean __assembly__ is compiled to __machine code__ by `JIT compiler`?

**Comment by hydai** [comment]
No. V8's TurboFan[1] will compile javascript(source code) and wasm(assembly) to its own bytecode(IR). And then compile its IR to machine code at the runtime.
That's why I said that V8 can be worked as a JIT compiler.

But ssvmc compile the wasm(assembly) to machine code directly. That's why I said that SSVM supports AOT compilation.


[1]: https://v8.dev/docs/turbofan

**Comment by Litrop** [comment]
Use IR not equal to JIT compiler. LLVM use IR too.
I prefer to say v8 does twice AOT compilation with different level of optimizations.

**Comment by hydai** [comment]
I don't think so. LLVM uses IR at the compilation stage, not the runtime stage. But V8 does.
They said at their blog: https://v8.dev/blog/turbofan-jit

Another example is Java. Java is compiled to Java Bytecode. And then the JVM(JIT compiler) will compile Java Bytecode to machine code at the runtime. Do the compilation at the runtime is the point. Not use IR means it is a JIT compiler.

**Comment by Litrop** [comment]
To simplify question,
Do you agree that it's AOT compilation when Liftoff only mode or TurboFan only mode?

https://v8.dev/docs/wasm-compilation-pipeline#flags-for-experimentation
> Liftoff only:
> 
> In V8, set the --liftoff --no-wasm-tier-up flags.
> In Chrome, disable WebAssembly tiering (chrome://flags/#enable-webassembly-tiering) and enable WebAssembly baseline compiler (chrome://flags/#enable-webassembly-baseline).
> TurboFan only:
> 
> In V8, set the --no-liftoff --no-wasm-tier-up flags.
> In Chrome, disable WebAssembly tiering (chrome://flags/#enable-webassembly-tiering) and disable WebAssembly baseline compiler (chrome://flags/#enable-webassembly-baseline).

**Comment by hydai** [comment]
Liftoff -> Yes.

It compiles the wasm to native directly.

TurboFan -> No.

As far as I know, the TurboFan will compile those hot code snippets. It depends on the runtime behavior to do the just-in-time compilation.

**Comment by Litrop** [comment]
https://docs.google.com/presentation/d/1H1lLsbclvzyOF3IUR05ZUaZcqDxo7_-8f4yJoxdMooU/edit#slide=id.g15785de102_0_2
Javascript and WASM have different pipeline.

**Comment by hydai** [comment]
Oh, got it. So the pipeline is different. Thanks for your information 👍
