### ISSUE TITLE
I can't pull the secondstate/ssvm

### ISSUE THREAD

**Issue by Jessicajin-lab** [second-state/SSVM#3]
Hello,
I tried to use the secondstate/ssvm docker image with these commands:
"$ docker pull secondstate/ssvm:dev-0.3.0" ,and "docker pull secondstate/ssvm"
But I always recieve an Error:"Error response from daemon: manifest for secondstate/devchain:latest not found: manifest unknown: manifest unknown"
I want to know if the docker image is available? Thank you~

**Comment by hydai** [comment]
Hi @Jessicajin-lab 
We found that our dockerhub encounter some issues, so the docker image is broken.
I have uploaded the correct image to dockerhub just now, please try again. Thanks.

**Comment by Jessicajin-lab** [comment]
Thank you@hydai,
I've pulled the image successfully. But I encounter another problem.
I can run 'built-in tests' successfully. But when I run the examples of ssvm-evm, ssvm-proxy and ssvm, I can't get the right responses as the examples in Readme. The responses from bash are the same, which is  "No such file or directory".
![图片](https://user-images.githubusercontent.com/58798100/71881588-8de4cd80-316d-11ea-9569-eb4200b0d6c0.png)
![图片](https://user-images.githubusercontent.com/58798100/71882211-faac9780-316e-11ea-917d-bbb80cc39c11.png)
![图片](https://user-images.githubusercontent.com/58798100/71882224-039d6900-316f-11ea-93b2-f81f49b3551a.png)

bash: ./ssvm-evm: No such file or directory
bash: ./ssvm-proxy: No such file or directory
bash: ./ssvm: No such file or directory

I still don't know how to deal with this problem. I'll appriciate it if you can give me some suggestions. Thank you.

**Comment by hydai** [comment]
Please notice that you have to `cd <path/to/ssvm/build_folder>` first in the beginning of all command.

**Comment by Jessicajin-lab** [comment]
According to your suggestion, I've solved this problem and run the examples successfully.
Thank you very much.
