### ISSUE TITLE
Add an ssvm-qitc example

### ISSUE THREAD

**Issue by robinvanemden** [second-state/SSVM#4]
`SSVM` is really nice! I particularly like the `ONNC` support. Would it be possible to add a minimal example that demonstrates how to get from an ONNX model to running it with `ssvm-qitc`?

**Comment by hydai** [comment]
Hi @robinvanemden,

Sure thing. The release of ONNC-WebAssembly backend will be announced in the next few weeks. `ssvm-qitc` will need the library support from ONNC-WebAssembly runtime to execute. We will notify 
 you when the demonstration is available. Thanks.

**Comment by robinvanemden** [comment]
Hi @hydai, that's great!

**Comment by hydai** [comment]
Yes, SSVM-QITC is a collaborative project between Second State Inc. and Skymizer Inc. And we are going to freeze the code and prepare the public release of ONNC WebAssembly backend.

Also, your given link is not the official repo and it seems to be out of date. Please refer to the [official ONNC repo](https://github.com/ONNC/onnc) for the latest updates.

**Comment by robinvanemden** [comment]
Very cool! I corrected the link to the ONNC repository - I meant to link to it from the start, but did a mobile GitHub search for the repo and apparently inadvertently linked to a cloned repo.
Anyway, I am very much looking forward to the public release of the ONNC WebAssembly backend!

**Comment by hydai** [comment]
Hi @robinvanemden,
We've put our preview version of ONNC WebAssembly backend on GitHub.
You can access it via [onnc-wasm](https://github.com/ONNC/onnc-wasm).
Please let me know if you encounter any issue when using our toolchain.

**Comment by robinvanemden** [comment]
Hi @hydai,
Thank you - that's great! I will, of course, keep you informed on any issues I might encounter.

**Comment by hydai** [comment]
We've updated the [ONNC-Wasm](https://github.com/ONNC/onnc-wasm) repository for the [ISCA 2020 tutorial](https://www.iscaconf.org/isca2020/program/workshops.php#onnc).
And here is [the pre-recorded video for `ssvm-qitc`](https://www.youtube.com/watch?v=cbiPuHMS-iQ).
