### ISSUE TITLE
Add options to CMake in order to select the VM to build

### ISSUE THREAD

**Issue by axic** [second-state/SSVM#6]
Currently CMake enables all targets, including ssvm-aot, which requires llvm.

It would be nice to have the ability to only build the interpreter and not depending on llvm in that case.

**Comment by hydai** [comment]
Hi @axic 
We add a cmake option `SSVM_DISABLE_AOT_RUNTIME`. The AOT runtime and `ssvm-aot` will not be built when you set `-DSSVM_DISABLE_AOT_RUNTIME=ON`.

And we released [SSVM 0.6.0](https://github.com/second-state/SSVM/releases/tag/0.6.0) which refactors lots of components and fix several issues.

**Comment by axic** [comment]
Nice, thank you very much!
