### ISSUE TITLE
`fd_close` on stdin returns error

### ISSUE THREAD

**Issue by yagehu** [second-state/SSVM#74]
I'm writing small programs in text format to test WASI support of various runtimes (eg. Wasmtime, Wasmer, etc.). I have this program to test `fd_close`:

```wat
(module
  (type (;0;) (func))
  (type (;1;) (func (param i32)))
  (type (;2;) (func (param i32) (result i32)))

  (import "wasi_snapshot_preview1" "fd_close" (func $__wasi_fd_close (type 2)))
  (import "wasi_snapshot_preview1" "proc_exit"
    (func $__wasi_proc_exit (type 1))
  )

  (func $_start (type 0)
    (call $__wasi_fd_close (i32.const 0))
    call $__wasi_proc_exit
  )

  (memory (;0;) (export "memory") 1)

  (export "_start" (func $_start))
)
```

Running the compiled `.wasm` file on other runtimes return a `0` status code indicating success. But running this on SSVM gives me status code 58. Any idea why?

**Comment by hydai** [comment]
Hi @yagehu , Thanks for your report.

@q82419 Please reproduce this issue.

**Comment by q82419** [comment]
Thanks for reporting. Fixed it in PR.
